import mongoose, { Schema } from "mongoose"
import jwt from "jsonwebtoken"
import bcrypt from "bcrypt"


const userSchema = new mongoose.Schema({
    username: {
        type: String,
        required: true,
        unique: true,
        trim: true,
        index: true,
        lowercase: true
    },
    email: {
        type: String,
        required: true,
        unique: true,
        trim: true,
        lowercase: true
    },
    fullname: {
        type: String,
        required: true,
        index: true,
        trim: true,
    },
    avatar: {
        type: String,
        required: true,
    },
    coverImage: {
        type: String,
    },
    watchhistory: [
        {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Video"
        }
    ],
    password: {
        type: String,
        required: [true, "Password is required"],
    },
    refreshTokens: {
        type: String
    }
}, { timestamps: true })

userSchema.pre("save", async function () {
    if (!this.isModified("password")) return;

    this.password = await bcrypt.hash(this.password, 10);
});

// method to compare password
// this method will be used during login to verify the password
// entered by the user with the hashed password stored in the database
// bcrypt.compare() takes care of hashing the entered password and comparing it with the stored hash
// it returns true if they match, false otherwise  
// we are using function() instead of arrow function to have access to 'this' keyword
// 'this' refers to the current user document
userSchema.methods.isCorrectPassword = async function (password) {
    return await bcrypt.compare(password, this.password)
}

// jwt is a birorary token that is used to authenticate users
// it is a string that is generated by the server and sent to the client
// the client then sends the token back to the server with each request
// the server then verifies the token and grants access to the requested resource

userSchema.methods.generateJwtToken = function () {
    return jwt.sign({
        _id: this._id,
        username: this.username,
        email: this.email,
        fullname: this.fullname
    }, 
    process.env.ACCESS_TOKEN_SECRET, { 
        expiresIn: process.env.ACCESS_TOKEN_EXPIRES_IN 
    }
)
}



userSchema.methods.generateRefreshToken = function () { 

    return jwt.sign({
        _id: this._id,
       
    }, 
    process.env.REFRESH_TOKEN_SECRET, { 
        expiresIn: process.env.REFRESH_TOKEN_EXPIRES_IN 
    }
)

}


const User = mongoose.model("User", userSchema)

export default User